### ISSUE TITLE
Explorador y Neutralizador deben tener en cuenta la energía.

### ISSUE THREAD

**Issue by miguelis** [tutugordillo/SIDEMA#24]
El explorador sigue explorando casillas hasta que se queda sin batería, en su último aliento explora la última y luego se queda parado.

El neutralizador solo va a ser enviado a una casilla cuando el cc sabe que no va a quedarse sin energía en ningún caso. 

Faltaría decidir qué hacemos cuando no hay ningún explorador que pueda seguir explorando o ningún neutralizados que siga desactivando.

Aunque la funcionalidad que hay hasta este momento nos serviría para modelar que podría haber robots defectuosos y que aún así nuestro programa sigue funcionando correctamente pese a ello. No obstante, en la vida real, se presupone que la mayor parte de estos tienen batería suficiente, o que en cualquier caso podrían incorporarse a posterior nuevos robots y que por lo tanto estas situaciones no son preocupantes.

**Comment by tutugordillo** [comment]
Hecho
